# Generated by Django 5.0.6 on 2024-06-18 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField()),
                ('sub_code', models.CharField(max_length=15)),
                ('sub_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cie', models.IntegerField()),
                ('marks', models.DecimalField(decimal_places=2, max_digits=4)),
                ('attendance', models.CharField(max_length=10)),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_usn', to='main.students')),
                ('sub_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_code', to='main.subject')),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='counsellor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counsellor', to='main.teachers'),
        ),
    ]
