# Generated by Django 5.0.6 on 2024-06-26 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CIE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cie', models.IntegerField()),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updated.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=100)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('attendance', models.CharField(max_length=50)),
                ('cie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updated.cie')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updated.student')),
            ],
        ),
    ]
