# Generated by Django 5.0.6 on 2024-07-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updated', '0002_teacherdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cie',
            name='sub_code',
            field=models.CharField(default='21CS11', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='usn',
            field=models.CharField(default='1RF21CS005', max_length=100),
            preserve_default=False,
        ),
    ]
